/**
 * Audit report export - PDF and CSV
 */

import PDFDocument from 'pdfkit';

/**
 * Generate PDF report for an audit
 * @param {object} audit - Audit with issues, project
 * @param {object} project - Project with name, url
 * @returns {Promise<Buffer>}
 */
export async function generatePdf(audit, project) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    const doc = new PDFDocument({ margin: 50 });
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const date = audit.completed_at
      ? new Date(audit.completed_at).toLocaleDateString()
      : new Date().toLocaleDateString();

    doc.fontSize(20).text('Audit Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).text(project?.name || 'Project', { align: 'center' });
    doc.text(project?.url || audit.url || '', { align: 'center' });
    doc.text(`Generated: ${date}`, { align: 'center' });
    doc.moveDown(2);

    doc.fontSize(14).text('Scores', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(11);
    doc.text(`SEO: ${audit.seo_score ?? '-'}/100`);
    doc.text(`AEO: ${audit.aeo_score ?? '-'}/100`);
    doc.text(`GEO: ${audit.geo_score ?? '-'}/100`);
    if (audit.ai_citation_score != null) {
      doc.text(`AI Citation: ${audit.ai_citation_score}/100`);
    }
    doc.text(`Pages analyzed: ${audit.pages_crawled ?? 1}`);
    doc.moveDown(2);

    doc.fontSize(14).text('Issues', { underline: true });
    doc.moveDown(0.5);

    const issues = audit.issues || [];
    if (issues.length === 0) {
      doc.text('No issues found.');
    } else {
      doc.fontSize(10);
      for (let i = 0; i < issues.length; i++) {
        const issue = issues[i];
        const pages = issue.meta?.pages?.length
          ? ` (${issue.meta.pages.length} pages)`
          : issue.meta?.page
            ? ` (${issue.meta.page})`
            : '';
        doc.text(`${i + 1}. [${issue.category.toUpperCase()}] ${issue.severity}: ${issue.title}${pages}`);
        doc.text(`   Impact: ${issue.impact}`);
        doc.text(`   Fix: ${issue.fix}`);
        doc.moveDown(0.5);
      }
    }

    doc.moveDown(2);
    doc.fontSize(9).text('Generated by Searchlyst - AI Visibility Audit', { align: 'center' });

    doc.end();
  });
}

/**
 * Generate CSV report for an audit
 * @param {object} audit - Audit with issues
 * @param {object} project - Project with name, url
 * @returns {string}
 */
export function generateCsv(audit, project) {
  const headers = ['Category', 'Severity', 'Title', 'Impact', 'Fix', 'Pages'];
  const rows = [headers.join(',')];

  const escape = (s) => {
    const str = String(s ?? '').replace(/"/g, '""');
    return str.includes(',') || str.includes('"') || str.includes('\n') ? `"${str}"` : str;
  };

  const issues = audit.issues || [];
  for (const issue of issues) {
    const pages = issue.meta?.pages?.length
      ? issue.meta.pages.join('; ')
      : issue.meta?.page
        ? issue.meta.page
        : '';
    rows.push([
      escape(issue.category),
      escape(issue.severity),
      escape(issue.title),
      escape(issue.impact),
      escape(issue.fix),
      escape(pages),
    ].join(','));
  }

  return rows.join('\n');
}
